name: Deploy Discord Bot - Development Build
on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          port: ${{ secrets.SSH_PORT_DEV }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir /opt/${BUILD_ENV}-discordbot 2>/dev/null
            cd /opt
            git clone --branch ${BUILD_ENV} github-desaerun:desaerun/discordhistorybot.git ${BUILD_ENV}-discordbot 2>/dev/null
            cd ${BUILD_ENV}-discordbot
            cp ~/.env .env
            git stash
            git fetch origin ${BUILD_ENV}
            git merge -s recursive -X theirs origin/${BUILD_ENV}
            npm install
            pm2 stop all 2>/dev/null
            pm2 start main.js